routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/admin/login', function () {
    return view('auth.login');
});


Route::group( [ 'namespace' => 'admin'], function()
{
    Route::get('home', 'HomeController@home')->name('home');
    Route::get('charts', 'HomeController@chart')->name('chart');
});

Route::group( [ 'prefix' => 'admin' , 'as' => 'admin.', 'namespace' => 'admin', 'middleware' => 'auth'], function()
{
    Route::resource('/restaurants', 'RestaurantController');
    Route::resource('/categories', 'CategoryController');
    Route::resource('/extra-categories', 'ExtraCategoryController');
    Route::resource('/delivery-addresses', 'DeliveryAddressController');
    Route::resource('/discounts', 'DiscountController');
    Route::resource('/extras', 'ExtraController');
    Route::resource('/foods', 'FoodController');
    Route::get('food/{id}/options','FoodController@getOptions')->name('foods.options');
    Route::resource('/options', 'OptionController');
    Route::post('food/{id}/options','OptionController@storeByFoodId')->name('foods.options');
    Route::get('food/{food_id}/option/{id}/update','OptionController@editByFoodId')->name('foods.options.edit');
    Route::put('food/{food_id}/option/{id}/update','OptionController@updateByFoodId')->name('foods.options.update');

    Route::resource('/orders', 'OrderController');
    Route::get('order/{id}/details','OrderController@getDetails')->name('order.details');
    Route::get('detail/{id}/extras','OrderDetailController@getExtras')->name('detail.extras');

    Route::resource('/blogs', 'BlogController');
    Route::resource('/footers', 'FooterController');
    Route::resource('/users', 'UserController');

    Route::post('category/{id}/extras','CategoryController@addExtra')->name('categories.extra');
    Route::get('category/{id}/foods','CategoryController@getFoods')->name('category.foods');
    Route::get('category/{id}/extras','ExtraCategoryController@getExtras')->name('category.get.extras');
    Route::post('option/{id}/extra','OptionController@addExtra')->name('option.extra');

    Route::resource('/feedbacks', 'FeedbackController');
    Route::resource('/policies', 'PolicyController');

    Route::post('category/{id}/foods','FoodController@storeByCategoryId')->name('category.foods');
    Route::post('category/{id}/extra','ExtraController@storeByCategoryId')->name('category.extras');

});

Route::prefix('admin')->group(function(){
    Auth::routes();
});

Route::get('/admin/home', 'HomeController@index')->name('home');

resources/views/includes/footer.blade.php
<!-- Footer -->
    <div class="container my-auto">
        <div class="copyright text-center my-auto">
            <span>Copyright &copy; HomeCoder 2021</span>
        </div>
    </div>

<!-- End of Footer -->

resources/views/includes/header.blade.php
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="">
<meta name="author" content="">

<title>Restaurant - Dashboard</title>

<!-- Custom fonts for this template-->

<link href="{!! asset('theme/vendor/fontawesome-free/css/all.css') !!}" rel="stylesheet" type="text/css">
<link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

<!-- Custom styles for this template-->
<link href="{!! asset('theme/css/image.css') !!}" rel="stylesheet">
<link href="{!! asset('theme/css/sb-admin-2.min.css') !!}" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css">

<link href="{!! asset('theme/vendor/datatables/dataTables.bootstrap4.css') !!}" rel="stylesheet">

<link rel="stylesheet" href="{!! asset('theme/css/select2.min.css') !!}">

resources/views/includes/sidebar.blade.php
<div id="wrapper">

    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

        <!-- Sidebar - Brand -->
        <a class="sidebar-brand d-flex align-items-center justify-content-center" href =#>
            <div class="sidebar-brand-icon rotate-n-15">
                <i class="fas fa-laugh-wink"></i>
            </div>
            <div class="sidebar-brand-text mx-3">Restaurant-Dashboard</div>
        </a>

        <!-- Divider -->
        <hr class="sidebar-divider my-0">

        <!-- Divider -->
        <hr class="sidebar-divider">

        <!-- Nav Item - Pages Collapse Menu -->
        <li class="nav-item">
            <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="true" aria-controls="collapsePages">
                <i class="fas fa-utensils"></i>
                <span>Food List</span>
            </a>
            <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
                <div class="bg-white py-2 collapse-inner rounded">
                    <a class="collapse-item" href = {{ route('admin.categories.index') }}>Categories</a>
                    <a class="collapse-item" href = {{ route('admin.foods.index') }}>Foods</a>
                    <a class="collapse-item" href = {{ route('admin.extra-categories.index') }}>Extra Categories</a>
                    <a class="collapse-item" href = {{ route('admin.extras.index') }}>Extras</a>
                </div>
            </div>
        </li>

        <li class="nav-item">
            <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages2" aria-expanded="true" aria-controls="collapsePages2">
                <i class="fas fa-wrench"></i>
                <span>Website Settings</span>
            </a>
            <div id="collapsePages2" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
                <div class="bg-white py-2 collapse-inner rounded">
                    <a class="collapse-item" href = {{ route('admin.restaurants.index') }}>Restaurant Info</a>
                    <a class="collapse-item" href = {{ route('admin.blogs.index') }}>Blogs Info</a>
{{--                    <a class="collapse-item" href = {{ route('admin.footers.index') }}>Footers Info</a>--}}
                    <a class="collapse-item" href = {{ route('admin.policies.index') }}>Policies Privacy</a>
                </div>
            </div>
        </li>

        <li class="nav-item">
            <a class="nav-link" href = {{ route('admin.delivery-addresses.index') }}>
                <i class="fas fa-truck"></i>
                <span>Delivery Addresses</span></a>
        </li>

        <li class="nav-item">
            <a class="nav-link" href = {{ route('admin.discounts.index') }}>
                <i class="fas fa-percent"></i>
                <span>Discounts</span></a>
        </li>

        <li class="nav-item">
            <a class="nav-link" href = {{ route('admin.orders.index') }}>
                <i class="fas fa-file-invoice-dollar"></i>
                <span>Orders</span></a>
        </li>

        <li class="nav-item">
            <a class="nav-link" href = {{ route('admin.users.index') }}>
                <i class="fas fa-user"></i>
                <span>Users</span></a>
        </li>

        <li class="nav-item">
            <a class="nav-link" href = {{ route('admin.feedbacks.index') }}>
                <i class="fas fa-comments"></i>
                <span>Feedback</span></a>
        </li>

        <!-- Divider -->
        <hr class="sidebar-divider d-none d-md-block">

        <!-- Sidebar Toggler (Sidebar) -->
        <div class="text-center d-none d-md-inline">
            <button class="rounded-circle border-0" id="sidebarToggle"></button>
        </div>

    </ul>
</div>