routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/admin/login', function () {
    return view('auth.login');
});


Route::group( [ 'namespace' => 'admin'], function()
{
    Route::get('home', 'HomeController@home')->name('home');
    Route::get('charts', 'HomeController@chart')->name('chart');
});

Route::group( [ 'prefix' => 'admin' , 'as' => 'admin.', 'namespace' => 'admin', 'middleware' => 'auth'], function()
{
    Route::resource('/restaurants', 'RestaurantController');
    Route::resource('/categories', 'CategoryController');
    Route::resource('/extra-categories', 'ExtraCategoryController');
    Route::resource('/delivery-addresses', 'DeliveryAddressController');
    Route::resource('/discounts', 'DiscountController');
    Route::resource('/extras', 'ExtraController');
    Route::resource('/foods', 'FoodController');
    Route::get('food/{id}/options','FoodController@getOptions')->name('foods.options');
    Route::resource('/options', 'OptionController');
    Route::post('food/{id}/options','OptionController@storeByFoodId')->name('foods.options');
    Route::get('food/{food_id}/option/{id}/update','OptionController@editByFoodId')->name('foods.options.edit');
    Route::put('food/{food_id}/option/{id}/update','OptionController@updateByFoodId')->name('foods.options.update');

    Route::resource('/orders', 'OrderController');
    Route::get('order/{id}/details','OrderController@getDetails')->name('order.details');
    Route::get('detail/{id}/extras','OrderDetailController@getExtras')->name('detail.extras');

    Route::resource('/blogs', 'BlogController');
    Route::resource('/footers', 'FooterController');
    Route::resource('/users', 'UserController');

    Route::post('category/{id}/extras','CategoryController@addExtra')->name('categories.extra');
    Route::get('category/{id}/foods','CategoryController@getFoods')->name('category.foods');
    Route::get('category/{id}/extras','ExtraCategoryController@getExtras')->name('category.get.extras');
    Route::post('option/{id}/extra','OptionController@addExtra')->name('option.extra');

    Route::resource('/feedbacks', 'FeedbackController');
    Route::resource('/policies', 'PolicyController');

    Route::post('category/{id}/foods','FoodController@storeByCategoryId')->name('category.foods');
    Route::post('category/{id}/extra','ExtraController@storeByCategoryId')->name('category.extras');

});

Route::prefix('admin')->group(function(){
    Auth::routes();
});

Route::get('/admin/home', 'HomeController@index')->name('home');

app/Http/Controllers/admin/DeliveryAddressController.php
<?php

namespace App\Http\Controllers\admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\DeliveryAddress\StoreDeliveryAddressRequest;
use App\Http\Requests\DeliveryAddress\UpdateDeliveryAddressRequest;
use App\Models\DeliveryAddress;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class DeliveryAddressController extends Controller
{
    private $index_view;
    private $create_view;
    private $edit_view;
    private $show_view;
    private $index_route;
    private $success_message;
    private $error_message;
    private $update_success_message;
    private $update_error_message;

    public function __construct()
    {
        $this->index_view   = 'admin.delivery_addresses.index';
        $this->create_view  = 'admin.delivery_addresses.create';
        $this->show_view    = 'admin.delivery_addresses.show';
        $this->edit_view    = 'admin.delivery_addresses.edit';
        $this->index_route  = 'admin.delivery-addresses.index';

        $this->success_message = trans('admin.created_successfully');
        $this->update_success_message = trans('admin.update_success');
        $this->error_message = trans('admin.fail_while_create');
        $this->update_error_message = trans('admin.fail_while_update');
    }
    public function index()
    {
        $delivery_addresses=DeliveryAddress::all();
        return view($this->index_view,compact('delivery_addresses'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view($this->create_view);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreDeliveryAddressRequest $request)
    {
        $validated_data = $request->validated();
        DB::beginTransaction();
        DeliveryAddress::create($validated_data);
        DB::commit();
        return redirect()->route($this->index_route)->with('error', $this->error_message);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $delivery_address=DeliveryAddress::find($id);
        return view ($this->edit_view,compact('delivery_address'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateDeliveryAddressRequest $request, $id)
    {
        $validated_data = $request->validated();
        DB::beginTransaction();
        $object = DeliveryAddress::find($id);
        $object->update($validated_data);
        DB::commit();
        return redirect()->route($this->index_route)->with('error', $this->update_error_message);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request,$id)
    {
        if ($request->ajax()) {
            $delivery_address = DeliveryAddress::findOrFail($id);
            $deleted =  $delivery_address->delete();
            if ($deleted) {
                return response()->json(['status' => 'success', 'message' => 'deleted_successfully']);
            } else {
                return response()->json(['status' => 'fail', 'message' => 'fail_while_delete']);
            }
        }
        return redirect()->route($this->index_route);
    }
}

app/Http/Controllers/dashboard/DeliveryAddressController.php
<?php

namespace App\Http\Controllers\dashboard;

use App\Helpers\Helper;
use App\Http\Controllers\Controller;
use App\Http\Requests\DeliveryAddress\StoreDeliveryAddressRequest;
use App\Http\Requests\DeliveryAddress\UpdateDeliveryAddressRequest;
use App\Models\DeliveryAddress;
use Illuminate\Http\Request;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;

class DeliveryAddressController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $addresses=DeliveryAddress::all();
        return response()->json(['msg'=>'All Delivery Addresses Received','addresses'=>$addresses],200);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreDeliveryAddressRequest $request)
    {
        $validated_data = $request->validated();
        DeliveryAddress::create($validated_data);
        return response()->json(['msg'=>'Added Succefully'],200);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateDeliveryAddressRequest $request, $id)
    {
        $validated_data = $request->validated();
        DB::beginTransaction();
        $object = DeliveryAddress::findOrFail($id);
        $object->update($validated_data);
        DB::commit();
        return response()->json(['msg'=>'Updated Successfully'],200);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        DB::beginTransaction();
        $address = DeliveryAddress::findOrFail($id);
        $deleted = $address->delete();
        DB::commit();
        if ($deleted) {
            return response()->json(['status' => 'success', 'message' => 'deleted_successfully']);
        } else {
            return response()->json(['status' => 'fail', 'message' => 'fail_while_delete']);
        }
    }
}

resources/views/admin/delivery_addresses/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="container-fluid">
        @include('flash-message')
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                        <h6 class="m-0 font-weight-bold text-primary">Create Delivery Address</h6>
                    </div>
                    <div class="card-body">
                        <form method="POST" action="{{ route('admin.delivery-addresses.store') }}">
                            @csrf
                            <div class="row">
                                <div class="form-group col-md-4">
                                    <label class="text-md-right">Name</label>
                                    <input type="text" class="form-control" name="name">
                                </div>
                                <div class="form-group col-md-4">
                                    <label class="text-md-right">Code</label>
                                    <input type="text" class="form-control" name="code">
                                </div>
                            </div>
                            <div class="row">
                                <div class="form-group col-md-4">
                                    <label class="text-md-right">Min Delivery</label>
                                    <input type="number" step="0.1" min="0" class="form-control" name="min_delivery">
                                </div>
                                <div class="form-group col-md-4">
                                    <label class="text-md-right">Delivery Cost</label>
                                    <input type="number" step="0.1" min="0" class="form-control" name="delivery_cost">
                                </div>
                            </div>
                            <div class="row">
                                <div class="form-group col-md-12 mb-0">
                                    <button type="submit" class="btn btn-primary">
                                        Save
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop

@section('scripts')
    <script>

    </script>

@endsection

resources/views/admin/delivery_addresses/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="container-fluid">
        @include('flash-message')
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                        <h6 class="m-0 font-weight-bold text-primary">Edit Delivery Address</h6>
                    </div>
                    <div class="card-body">
                        <form method="POST" action="{{ route('admin.delivery-addresses.update', $delivery_address->id) }}">
                            @csrf
                            @method('PUT')
                            <div class="row">
                                <div class="form-group col-md-4">
                                    <label class="text-md-right">Name</label>
                                    <input type="text" class="form-control" name="name" value="{{$delivery_address->name}}">
                                </div>
                                <div class="form-group col-md-4">
                                    <label class="text-md-right">Code</label>
                                    <input type="text" class="form-control" name="code" value="{{$delivery_address->code}}">
                                </div>
                            </div>
                            <div class="row">
                                <div class="form-group col-md-4">
                                    <label class="text-md-right">Min Delivery</label>
                                    <input type="number" step="0.1" min="0" class="form-control" name="min_delivery" value="{{$delivery_address->min_delivery}}">
                                </div>
                                <div class="form-group col-md-4">
                                    <label class="text-md-right">Delivery Cost</label>
                                    <input type="number" step="0.1" min="0" class="form-control" name="delivery_cost" value="{{$delivery_address->delivery_cost}}">
                                </div>
                            </div>
                            <div class="row">
                                <div class="form-group col-md-12 mb-0">
                                    <button type="submit" class="btn btn-primary">
                                        Save
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop

@section('scripts')
    <script>

    </script>

@endsection

resources/views/admin/delivery_addresses/index.blade.php
@extends('layouts.app')
@section('content')
    <!-- Main Content -->


    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        <h1 class="h3 mb-2 text-gray-800">Delivery Addresses</h1>

        <div class="row">
            <div class="col-lg-12">
                <div class="card shadow mb-4">
                    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                        <h6 class="m-0 font-weight-bold text-primary">Delivery Addresses</h6>
                        <a href="{{ route('admin.delivery-addresses.create') }}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm">
                            <i class="fas fa-plus fa-sm "></i>Add New Delivery Address</a>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered" id="dataTable">
                                <thead>
                                <tr>
                                    <th width="30">Name</th>
                                    <th width="30">Code</th>
                                    <th width="30">Min Delivery</th>
                                    <th width="30">Delivery Cost</th>
                                    <th width="120">Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($delivery_addresses as $delivery_address)
                                    <tr class="odd gradeX">
                                        <td>{{ $delivery_address->name }}</td>
                                        <td>{{ $delivery_address->code }}</td>
                                        <td>{{ $delivery_address->min_delivery }}</td>
                                        <td>{{ $delivery_address->delivery_cost }}</td>
                                        <td>
                                            <a href="{{ route('admin.delivery-addresses.edit',$delivery_address->id) }}" data-toggle="tooltip" title="Edit"><i class="fa fa-edit"></i></a> &nbsp; &nbsp;
                                            <a href="#" style="color: #dc3545" data-toggle="tooltip" title="Delete" onclick="event.preventDefault();deleteItem('{{ $delivery_address->id }}','{{ route('admin.delivery-addresses.destroy',$delivery_address->id) }}')"><i class="fa fa-trash"></i></a>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                        <!-- /.table-responsive -->
                    </div>
                </div>
            </div>
            <!-- /.col-lg-12 -->
        </div>
    </div>
    <!-- /.container-fluid -->
@stop

@section('scripts')
        <script src="{!! asset('theme/vendor/datatables/jquery.dataTables.min.js') !!}"></script>
        <script src="{!! asset('theme/vendor/datatables/dataTables.bootstrap4.min.js') !!}"></script>
        <script src="{!! asset('theme/js/demo/datatables-demo.js') !!}"></script>
        <script>
        function deleteItem(id,url) {
            swal({
                title: '{!! trans('Are You Sure ?') !!}',
                type: "warning",
                confirmButtonClass: "btn-danger",
                confirmButtonText: "{!! trans('Yes'); !!}",
                cancelButtonText: "{!! trans('No'); !!}",
                showCancelButton: true,
                closeOnConfirm: false,
                showLoaderOnConfirm: true
            }, function () {

                $.ajax({
                    url: url,
                    type: 'POST',
                    dataType: 'JSON',
                    data: {_token: '{!! csrf_token() !!}', _method : 'delete' }
                })
                    .done(function() {


                        swal({title: "{!! trans('Done') !!}", text: "{!! trans('Deleted Successfully') !!}", type: "success"},
                            function(){
                                location.reload();
                            }
                        );


                    })
                    .fail(function(e) {

                        swal("{!! trans('Fail') !!}",e.responseJSON.message, "error")

                    })
            });
        }
    </script>

@endsection