routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/admin/login', function () {
    return view('auth.login');
});


Route::group( [ 'namespace' => 'admin'], function()
{
    Route::get('home', 'HomeController@home')->name('home');
    Route::get('charts', 'HomeController@chart')->name('chart');
});

Route::group( [ 'prefix' => 'admin' , 'as' => 'admin.', 'namespace' => 'admin', 'middleware' => 'auth'], function()
{
    Route::resource('/restaurants', 'RestaurantController');
    Route::resource('/categories', 'CategoryController');
    Route::resource('/extra-categories', 'ExtraCategoryController');
    Route::resource('/delivery-addresses', 'DeliveryAddressController');
    Route::resource('/discounts', 'DiscountController');
    Route::resource('/extras', 'ExtraController');
    Route::resource('/foods', 'FoodController');
    Route::get('food/{id}/options','FoodController@getOptions')->name('foods.options');
    Route::resource('/options', 'OptionController');
    Route::post('food/{id}/options','OptionController@storeByFoodId')->name('foods.options');
    Route::get('food/{food_id}/option/{id}/update','OptionController@editByFoodId')->name('foods.options.edit');
    Route::put('food/{food_id}/option/{id}/update','OptionController@updateByFoodId')->name('foods.options.update');

    Route::resource('/orders', 'OrderController');
    Route::get('order/{id}/details','OrderController@getDetails')->name('order.details');
    Route::get('detail/{id}/extras','OrderDetailController@getExtras')->name('detail.extras');

    Route::resource('/blogs', 'BlogController');
    Route::resource('/footers', 'FooterController');
    Route::resource('/users', 'UserController');

    Route::post('category/{id}/extras','CategoryController@addExtra')->name('categories.extra');
    Route::get('category/{id}/foods','CategoryController@getFoods')->name('category.foods');
    Route::get('category/{id}/extras','ExtraCategoryController@getExtras')->name('category.get.extras');
    Route::post('option/{id}/extra','OptionController@addExtra')->name('option.extra');

    Route::resource('/feedbacks', 'FeedbackController');
    Route::resource('/policies', 'PolicyController');

    Route::post('category/{id}/foods','FoodController@storeByCategoryId')->name('category.foods');
    Route::post('category/{id}/extra','ExtraController@storeByCategoryId')->name('category.extras');

});

Route::prefix('admin')->group(function(){
    Auth::routes();
});

Route::get('/admin/home', 'HomeController@index')->name('home');

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $guarded = ['id', 'created_at', 'updated_at'];
    protected $hidden = ['created_at', 'updated_at'];

    public function foods(){
        return $this->hasMany(Food::class);
    }

    public function image()
    {
        return $this->morphOne(Image::class, 'imageable');
    }
    public  function discount(){
        return $this->hasMany(Discount::class);
    }

}

app/Http/Controllers/Api/CategoryController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\Category;
use Carbon\Carbon;
use Illuminate\Http\Request;
use phpDocumentor\Reflection\Types\Parent_;

class   CategoryController extends Controller
{

    /**
     * CategoryController constructor.
     */
    public function __construct()
    {
    }

    public  function  show(){
        $current_date=Carbon::now()->toDateTime();
        $day_name=$current_date->format('l');
        $categories=Category::with(['Discount'=>function ($query) use ($day_name){
            $query->select('category_id','amount')->where('day',$day_name);
        }])->orderBy('order')->get(['id','name']);
        if(!$categories->isEmpty()) {
            return response()->json(['msg' => 'All Categories Retrieved', 'Categories' => $categories],200,[],JSON_NUMERIC_CHECK);
        }
        else{
            return response()->json(['msg'=>'No Categories Found'],422);
        }

    }
    public  function  get(Request $request){
        $categories=Category::orderBy('order')->get(['id','name']);
        if(!$categories->isEmpty()) {
            return response()->json(['msg' => 'All Categories Retrieved', 'Categories' => $categories],200,[],JSON_NUMERIC_CHECK);
        }
        else{
            return response()->json(['msg'=>'No Categories Found'],422);
        }
    }
    public  function  all(Request $request){
    $categories=Category::with(['image'=>function($query){
        $query->select('imageable_id','image_path');
    },'foods'=>function($query){
        $query->select('id','category_id','name','description');
    },'foods.foodOption'=>function($query){
        $query->select(['food_id','price']);
    }])->orderBy('order')->get();
    return $categories;

    }

}

app/Http/Controllers/admin/CategoryController.php
<?php

namespace App\Http\Controllers\admin;

use App\Helpers\Helper;
use App\Http\Controllers\Controller;
use App\Http\Requests\Category\StoreCategoryRequest;
use App\Http\Requests\Category\UpdateCategoryRequest;
use App\Models\Category;
use App\Models\Extra;
use App\Models\FoodOption;
use App\models\FoodOptionExtra;
use App\models\Image;
use Illuminate\Http\Request;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;

class CategoryController extends Controller
{
    private $index_view;
    private $create_view;
    private $edit_view;
    private $show_view;
    private $index_route;
    private $success_message;
    private $error_message;
    private $update_success_message;
    private $update_error_message;

    public function __construct()
    {
        $this->index_view   = 'admin.categories.index';
        $this->create_view  = 'admin.categories.create';
        $this->show_view    = 'admin.categories.show';
        $this->edit_view    = 'admin.categories.edit';
        $this->index_route  = 'admin.categories.index';

        $this->success_message = trans('admin.created_successfully');
        $this->update_success_message = trans('admin.update_success');
        $this->error_message = trans('admin.fail_while_create');
        $this->update_error_message = trans('admin.fail_while_update');
    }
    public function index()
    {
        $extras =Extra::all();
        $categories=Category::all();
        return view($this->index_view,compact('categories','extras'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view($this->create_view);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreCategoryRequest $request)
    {
        $validated_data = $request->validated();
        DB::beginTransaction();
        $object = Category::create(Arr::except($validated_data, ['image']));
        if($request->hasFile('image')) {
            $image_data = Helper::uploadFileTo($validated_data["image"], 'categories');
            $image = Image::create([
                'image_path' => $image_data["media_path"],
                'is_primary' => 'yes'
            ]);
            $object->image()->save($image);
        }
        DB::commit();
        return redirect()->route($this->index_route)->with('error', $this->error_message);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category=Category::find($id);
        return view ($this->edit_view,compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateCategoryRequest $request, $id)
    {
        $validated_data = $request->validated();
        //dd($validated_data);
        DB::beginTransaction();
        $object = Category::find($id);
        $object->update($validated_data);
        Helper::handleImageReplace($request, $object, 'categories');
        DB::commit();
        return redirect()->route($this->index_route)->with('error', $this->update_error_message);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request,$id)
    {
        if ($request->ajax()) {
            DB::beginTransaction();
            $category = Category::findOrFail($id);
            $image = $category->image;
            $category->foods()->delete();
            $deleted = $category->delete();
            if ($image) {
                Storage::disk('public_images')->delete($image->image_path);
                $image->delete();
            }
            DB::commit();
            if ($deleted) {
                return response()->json(['status' => 'success', 'message' => 'deleted_successfully']);
            } else {
                return response()->json(['status' => 'fail', 'message' => 'fail_while_delete']);
            }
        }
        return redirect()->route($this->index_route);
    }

    public function addExtra(Request $request,$id){
        $category = Category::findOrFail($id);
        $extra_id = $request->extra_id;
        $price = $request->price;
        $foodIds = $category->foods->pluck('id');
        $foodOptionIds = FoodOption::whereIn('food_id',$foodIds)->pluck('id');
        foreach ($foodOptionIds as $foodOptionId)
        {
            FoodOptionExtra::create([
                'food_option_id'=> $foodOptionId,
                'extra_id' => $extra_id,
                'price' => $price
            ]);
        }
        return redirect()->route($this->index_route)->with('error', $this->error_message);

    }

    public function getFoods($id){
       $category = Category::findOrFail($id);
       $foods = $category->foods;
        return view ('admin.categories.foods',compact('foods','category'));
    }
}

app/Http/Controllers/dashboard/CategoryController.php
<?php

namespace App\Http\Controllers\dashboard;

use App\Helpers\Helper;
use App\Http\Controllers\Controller;
use App\Http\Requests\Category\StoreCategoryRequest;
use App\Http\Requests\Category\UpdateCategoryRequest;
use App\Models\Category;
use App\Models\Image;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories=Category::with('image:imageable_id,image_path')->orderBy('order')->get();
        return response()->json(['msg'=>'All Categories Received','categories'=>$categories],200);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreCategoryRequest $request)
    {
        $validated_data = $request->validated();
        DB::beginTransaction();
        $object = Category::create(Arr::except($validated_data, ['image']));
        if($request->hasFile('image')) {
            $image_data = Helper::uploadFileTo($validated_data["image"], 'categories');
            $image = Image::create([
                'image_path' => $image_data["media_path"],
                'is_primary' => 'yes'
            ]);
            $object->image()->save($image);
        }
        DB::commit();
        return response()->json(['msg'=>'Added Succefully'],200);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateCategoryRequest $request, $id)
    {
        $validated_data = $request->validated();
        //dd($validated_data);
        DB::beginTransaction();
        $object = Category::findOrFail($id);
        $object->update($validated_data);
        Helper::handleImageReplace($request, $object, 'categories');
        DB::commit();
        return response()->json(['msg'=>'Updated Successfully'],200);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        DB::beginTransaction();
        $category = Category::findOrFail($id);
        $image = $category->image;
        //$category->foods()->delete();
        $deleted = $category->delete();
        if ($image) {
            Storage::disk('public_images')->delete($image->image_path);
            $image->delete();
        }
        DB::commit();
        if ($deleted) {
            return response()->json(['status' => 'success', 'message' => 'deleted_successfully']);
        } else {
            return response()->json(['status' => 'fail', 'message' => 'fail_while_delete']);
        }
    }
}

resources/views/admin/categories/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="container-fluid">
        @include('flash-message')
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                        <h6 class="m-0 font-weight-bold text-primary">Create Category</h6>
                    </div>
                    <div class="card-body">
                        <form method="POST" enctype="multipart/form-data" action="{{ route('admin.categories.store') }}">
                            @csrf
                            <div class="row">
                                <div class="form-group col-md-4">
                                    <label class="text-md-right">Name</label>
                                    <input type="text" class="form-control" name="name" required>
                                </div>
                                <div class="form-group col-md-4">
                                    <label class="text-md-right">Priority</label>
                                    <input type="number" min="0" step="1" class="form-control" name="order">
                                </div>
                                <div class="form-group col-md-4">
                                    <label for="img">Image</label>
                                    <input class="form-control" type="file" id="img" name="image" accept="image/*">
                                </div>
                            </div>
                            <div class="row">
                                <div class="form-group col-md-4">
                                    <label class="text-md-right">Description</label>
                                    <textarea name="description" class="form-control" rows="4" cols="50"></textarea>
                                </div>
                            </div>
                            <div class="row">
                                <div class="form-group col-md-12 mb-0">
                                    <button type="submit" class="btn btn-primary">
                                        Save
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop

@section('scripts')
    <script>

    </script>

@endsection

resources/views/admin/categories/foods.blade.php
@extends('layouts.app')
@section('content')
    <!-- Main Content -->


    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        <h1 class="h3 mb-2 text-gray-800">{{ $category->name }} Foods</h1>

        <div class="row">
            <div class="col-lg-12">
                <div class="card shadow mb-4">
                    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                        <h6 class="m-0 font-weight-bold text-primary">{{ $category->name }}  Foods</h6>
                        <a data-toggle="modal" data-target="#food_create_modal" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm">
                            <i class="fas fa-plus fa-sm "></i>Add New Food to {{ $category->name }}</a>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered" id="dataTable">
                                <thead>
                                <tr>
                                    <th width="30">Name</th>
                                    <th width="50">Description</th>
                                    <th width="120">Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($foods as $food)
                                    <tr class="odd gradeX">
                                        <td>{{ $food->name }}</td>
                                        <td>{{ $food->description }}</td>
                                        <td>
                                            <a href="{{ route('admin.foods.edit',$food->id) }}" data-toggle="tooltip" title="Edit"><i class="fa fa-edit"></i></a> &nbsp; &nbsp;
                                            <a href="#" style="color: #dc3545" data-toggle="tooltip" title="Delete" onclick="event.preventDefault();deleteItem('{{ $food->id }}','{{ route('admin.foods.destroy',$food->id) }}')"><i class="fa fa-trash"></i></a>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                        <!-- /.table-responsive -->
                    </div>
                </div>
            </div>
            <!-- /.col-lg-12 -->
        </div>
    </div>
    <!-- /.container-fluid -->
    <div class="modal fade" id="food_create_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"></button>
                    <h4 class="modal-title" id="myModalLabel">New Food to {{ $category->name }}</h4>
                </div>
                <div class="modal-body">
                    <form action="{{ route('admin.category.foods',$category->id) }}" method="POST" id="food_create_form" enctype="multipart/form-data">
                        @csrf
                        <div class="form-group has-feedback {{ $errors->has('name') ? 'has-error' : '' }}">
                            <label>Name</label>
                            <input type="text" class="form-control" name="name" value="{{ old('name') }}">
                            @if ($errors->has('name'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('name') }}</strong>
                                </span>
                            @endif
                        </div>
                        <div class="form-group has-feedback {{ $errors->has('description') ? 'has-error' : '' }}">
                            <label>Description</label>
                            <textarea name="description" cols="30" rows="10" class="form-control">{{ old('description') }}</textarea>
                            @if ($errors->has('description'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('description') }}</strong>
                                </span>
                            @endif
                        </div>
                        <div class="form-group has-feedback {{ $errors->has('image') ? 'has-error' : '' }}">
                            <label>Image</label>
                            <input type="file" name="image">
                            @if ($errors->has('image'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('image') }}</strong>
                                </span>
                            @endif
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" onclick="SubmitForm('food_create_form')">Save
                        changes
                    </button>
                </div>
            </div>
        </div>
    </div>

@stop

@section('scripts')
    <script src="{!! asset('theme/vendor/datatables/jquery.dataTables.min.js') !!}"></script>
    <script src="{!! asset('theme/vendor/datatables/dataTables.bootstrap4.min.js') !!}"></script>
    <script src="{!! asset('theme/js/demo/datatables-demo.js') !!}"></script>
    <script>
        function deleteItem(id,url) {
            swal({
                title: '{!! trans('Are You Sure ?') !!}',
                type: "warning",
                confirmButtonClass: "btn-danger",
                confirmButtonText: "{!! trans('Yes'); !!}",
                cancelButtonText: "{!! trans('No'); !!}",
                showCancelButton: true,
                closeOnConfirm: false,
                showLoaderOnConfirm: true
            }, function () {

                $.ajax({
                    url: url,
                    type: 'POST',
                    dataType: 'JSON',
                    data: {_token: '{!! csrf_token() !!}', _method : 'delete' }
                })
                    .done(function() {


                        swal({title: "{!! trans('Done') !!}", text: "{!! trans('Deleted Successfully') !!}", type: "success"},
                            function(){
                                location.reload();
                            }
                        );


                    })
                    .fail(function(e) {

                        swal("{!! trans('Fail') !!}",e.responseJSON.message, "error")

                    })
            });
        }
        function SubmitForm(formId)
        {
            $('#'+formId).submit();
        }
    </script>
@endsection

resources/views/admin/categories/index.blade.php
@extends('layouts.app')
@section('content')
    <!-- Main Content -->


    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        <h1 class="h3 mb-2 text-gray-800">Categories</h1>

        <div class="row">
            <div class="col-lg-12">
                <div class="card shadow mb-4">
                    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                        <h6 class="m-0 font-weight-bold text-primary">Categories</h6>
                        <a href="{{ route('admin.categories.create') }}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm">
                            <i class="fas fa-plus fa-sm "></i>Add New Category</a>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered" id="dataTable">
                                <thead>
                                <tr>
                                    <th width="30">Name</th>
                                    <th width="30">Priority</th>
                                    <th width="50">Description</th>
                                    <th width="120">Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($categories as $category)
                                    <tr class="odd gradeX">
                                        <td>{{ $category->name }}</td>
                                        <td>{{ $category->order }}</td>
                                        <td>{{ $category->description }}</td>
                                        <td>
                                            <a href="{{ route('admin.categories.edit',$category->id) }}" data-toggle="tooltip" title="Edit"><i class="fa fa-edit"></i></a> &nbsp; &nbsp;
                                            <a href="#" style="color: #dc3545" data-toggle="tooltip" title="Delete" onclick="event.preventDefault();deleteItem('{{ $category->id }}','{{ route('admin.categories.destroy',$category->id) }}')"><i class="fa fa-trash"></i></a>
                                            &nbsp;&nbsp;
                                            <a data-toggle="tooltip" onclick="addExtra('{{ $category->id }}')" style="color: #23ff64" title="Add Extra"><i class="fas fa-plus"></i></a> &nbsp; &nbsp;
                                            <a href="{{ route('admin.category.foods',$category->id) }}" style="color: #ff9d06" data-toggle="tooltip" title="View Foods"><i class="fa fa-eye"></i></a>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                        <!-- /.table-responsive -->
                    </div>
                </div>
            </div>
            <!-- /.col-lg-12 -->
        </div>
    </div>
    <!-- /.container-fluid -->
    <!-- /.container-fluid -->
    <div class="modal fade" id="add_extra_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"></button>
                    <h4 class="modal-title" id="myModalLabel">Add Extra To Category</h4>
                </div>
                <div class="modal-body">
                    <form action="" method="POST" id="add_extra_form">
                        @csrf
                        <div class="form-group has-feedback {{ $errors->has('extra') ? 'has-error' : '' }}">
                            <label for="extra">Extra</label>
                            <select name="extra_id" id="extra" class="form-control">
                                @foreach($extras as $extra)
                                    <option value="{{ $extra->id }}">{{ $extra->name }}</option>
                                @endforeach
                            </select>
                            @if ($errors->has('extra'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('extra') }}</strong>
                                </span>
                            @endif
                        </div>
                        <div class="form-group has-feedback {{ $errors->has('price') ? 'has-error' : '' }}">
                            <label for="price">Price</label>
                            <input name="price" id="price" type="number" min="0" step="0.1" class="form-control">
                            @if ($errors->has('price'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('price') }}</strong>
                                </span>
                            @endif
                        </div>
                    </form>
            </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" onclick="SubmitForm('add_extra_form')">Save
                        changes
                    </button>
                </div>
            </div>
        </div>
    </div>

@stop

@section('scripts')
        <script src="{!! asset('theme/vendor/datatables/jquery.dataTables.min.js') !!}"></script>
        <script src="{!! asset('theme/vendor/datatables/dataTables.bootstrap4.min.js') !!}"></script>
        <script src="{!! asset('theme/js/demo/datatables-demo.js') !!}"></script>
        <script>
        function deleteItem(id,url) {
            swal({
                title: '{!! trans('Are You Sure ?') !!}',
                type: "warning",
                confirmButtonClass: "btn-danger",
                confirmButtonText: "{!! trans('Yes'); !!}",
                cancelButtonText: "{!! trans('No'); !!}",
                showCancelButton: true,
                closeOnConfirm: false,
                showLoaderOnConfirm: true
            }, function () {

                $.ajax({
                    url: url,
                    type: 'POST',
                    dataType: 'JSON',
                    data: {_token: '{!! csrf_token() !!}', _method : 'delete' }
                })
                    .done(function() {


                        swal({title: "{!! trans('Done') !!}", text: "{!! trans('Deleted Successfully') !!}", type: "success"},
                            function(){
                                location.reload();
                            }
                        );


                    })
                    .fail(function(e) {

                        swal("{!! trans('Fail') !!}",e.responseJSON.message, "error")

                    })
            });
        }
        function SubmitForm(formId) {
            $('#'+formId).submit();
        }
    </script>

    <script>
        function addExtra(catId) {
            var modalObj = $('#add_extra_modal');
            var url = '{{ route("admin.categories.extra", ":id") }}';
            url = url.replace(':id', catId);
            modalObj.find('form').attr('action',url);
            modalObj.modal('show');
        }
    </script>

@endsection